```{r}
library(XML)
library(xml2)
library(rvest)
library(magrittr)
# Assemble url (so it fits on screen)
basket <- "https://www.basketball-reference.com"
gsw <- "/teams/GSW/2017.html"
gsw_url <- paste0(basket, gsw)

# download HTML file to your working directory
download.file(gsw_url, 'gsw-roster-2017.html')

# Read GSW Roster html table
gsw_roster <- readHTMLTable('gsw-roster-2017.html')

# Assemble url (so it fits on screen)
basket <- "https://www.basketball-reference.com"
bos <- "/teams/BOS/2017.html"
bos_url <- paste0(basket, bos)

# download HTML file to your working directory
download.file(bos_url, 'bos-roster-2017.html')

# Read BOS Roster html table
bos_roster <- readHTMLTable('bos-roster-2017.html')
```

```{r}
nba_html <- paste0(basket, "/leagues/NBA_2017.html")
download.file(nba_html, 'nba-2017.html')

xml_doc <- read_html(nba_html)
xml_text <- xml_doc %>% html_text()

# content of h2 nodes
a = xml_doc %>%
  html_nodes("h2") %>%
  html_text() 

b = xml_doc %>%
  html_nodes("h1") %>%
  html_text() 

c = xml_doc %>%
  html_nodes("strong") %>%
  html_text() 

d = xml_doc %>%
  html_nodes("button") %>%
  html_text() 

# node with an attribute
xml_doc %>%
  html_nodes("p.listhead") %>%
  html_text()

xml_doc %>%
  html_nodes(xpath = '//p[@class="listhead"]') %>%
  html_text()

xml_doc %>%
  html_nodes(xpath = '//ul[@class=""]/li/a') %>%
  html_text()

# extracting first table 
xml_table1 <- xml_doc %>%
  html_nodes("table") %>%
  extract(1)

class(xml_table1)

tbl1 <- html_table(xml_table1)

head(tbl1)
```
```{r}
# extracting second table 
xml_table2 <- xml_doc %>%
  html_nodes("table") %>%
  extract(2)

# two html tables
xml_tables <- xml_doc %>%
  html_nodes("table") %>%
  extract(1:2)

# extract names of teams
xml_tables %>% 
  html_nodes("a") %>%
  html_text()

# href attributes
hrefs = xml_tables %>% 
  html_nodes("a") %>%
  html_attr("href")
 
teams = substr(hrefs,8,10)

files=character()

for(i in teams){
  files = c(files,paste0(i,"-roster-2017.html"))
}

team_url = character()

for(i in hrefs){
  team_url = c(team_url,paste0(basket,i))
}

for(i in 1:length(team_url)){
  download.file(team_url[i],files[i])
}

x = read_html(team_url[1])

# extracting first table 
roster <- x %>%
  html_nodes("table") %>%
  extract(1)
roster = html_table(roster)
write.csv(roster,file="BOS-roster-2017.csv")

files1=character()
for(i in teams){
  files1 = c(files1,paste0(i,"-roster-2017.csv"))
}

for(i in 1:length(files1)){
  x = read_html(team_url[i])

# extracting first table 
roster <- x %>%
  html_nodes("table") %>%
  extract(1)
roster = html_table(roster)
write.csv(roster,file=files1[i])
}

read.csv("POR-roster-2017.csv")
```
challenge
```{r}
a=data.frame()
for(i in 1:length(teams)){
  b = read.csv(files1[i])
  b$team = teams[i]
  a = rbind(a,b)
}
write.csv(a,"nba-rosters-2017.csv")
```



